config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                       Controller#Action
#                     root GET    /                                 pages#home
#                     home GET    /home(.:format)                   pages#home
#                   inside GET    /inside(.:format)                 pages#inside
#         new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#            user_password POST   /users/password(.:format)         devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                          PATCH  /users/password(.:format)         devise/passwords#update
#                          PUT    /users/password(.:format)         devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#        user_registration POST   /users(.:format)                  devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                          PATCH  /users(.:format)                  devise/registrations#update
#                          PUT    /users(.:format)                  devise/registrations#update
#                          DELETE /users(.:format)                  devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                          GET    /users/confirmation(.:format)     devise/confirmations#show
#               admin_root GET    /admin(.:format)                  admin/base#index
#              admin_users GET    /admin/users(.:format)            admin/users#index
#                          POST   /admin/users(.:format)            admin/users#create
#           new_admin_user GET    /admin/users/new(.:format)        admin/users#new
#          edit_admin_user GET    /admin/users/:id/edit(.:format)   admin/users#edit
#               admin_user GET    /admin/users/:id(.:format)        admin/users#show
#                          PATCH  /admin/users/:id(.:format)        admin/users#update
#                          PUT    /admin/users/:id(.:format)        admin/users#update
#                          DELETE /admin/users/:id(.:format)        admin/users#destroy
#

Ttdx3::Application.routes.draw do
  root "pages#about"
  
  get 'activities/index'

  resources :solutions
  get 'tags/:tag', to: 'things#index', as: :tag
  resources :things
  resources :comments
  resources :activities
  resources :registration_steps
  

  get "home_alt", to: "things#home_alt"
    

  
  get "inside", to: "pages#inside", as: "inside"

  
  get "follow", to: "things#follow", as: "follow"
  get "unfollow", to: "things#unfollow", as: "unfollow"
    
  get "current_user_things", to: "things#index_current_user", as: "current_user_things"
  
  
#  devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }

  
#  get "home_alt", to: "pages#home_alt"
  
    
   
    
  namespace :admin do
    root "base#index"
    resources :users
    
  end

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  include PublicActivity::Model
  validates :object_description, presence: true, length: { maximum: 200 }
  validates :tag_list, length: { maximum: 100 }
  validates :solution_description, length: { maximum: 2000 }
  validates :problem_description, length: { maximum: 2000 }    

  #REQUIRES USER_ID EXCEPT FOR INITIAL SIGNUP ACTION
#  tracked owner: ->(controller, model) { controller.current_user }, unless: :user_not_required?
#  validates :user_id, presence: true, unless: :user_not_required?  #REQUIRES USER_ID EXCEPT FOR INITIAL SIGNUP ACTION
    
  has_many :solutions
  has_many :comments
  accepts_nested_attributes_for :solutions

  belongs_to :user  


  attr_accessor :user_not_required

  
  default_scope -> { order(updated_at: :desc) }

  acts_as_taggable
  
  
  
  def self.search_and_order(search, page_number)
    if search
      where("object_description LIKE ?", "%#{search.downcase}%").order(updated_at: :asc).page page_number
    else
      order(updated_at: :asc).page page_number
    end
  end
  
  def user_not_required? 
    user_not_required == 'true' || user_not_required == true
  end

  
  
end


#taylor added

app/controllers/things_controller.rb
class ThingsController < ApplicationController
#  before_filter :require_signed_in!, unless: :user_not_required?
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  def home_alt
    @thing = Thing.new
#    @user.things.build
#    @thing.user_not_required == true     
  end  
  
  # GET /things
  # GET /things.json
  def index
    if params[:tag]
      @things = Thing.tagged_with(params[:tag]).page params[:page]
    else
      @things = Thing.all.search_and_order(params[:search], params[:page])
    end
    @followed_things_ids = current_user.followed_things.map(&:to_i)
  end
  
  def index_current_user
    @things = current_user.things
    ft = current_user.followed_things
    ft = Thing.find(ft)
    @followed_things = ft
    @followed = false
    
  end
  # GET /things/1
  # GET /things/1.json

  def follow
    id_s = params[:format]
    id = id_s.to_i
    current_user.followed_things_will_change!
    if current_user.followed_things.nil? 
      current_user.update_attribute(:followed_things, [id])
      current_user.create_activity :thing_followed, owner: current_user
    else
      unless current_user.followed_things.include? id_s
        current_user.update_attributes(followed_things: current_user.followed_things.push(id))
        #set target type to the object being followed
        current_user.create_activity action: 'thing_followed', owner: current_user, relevant_obj_id: id
      end
    end
    current_user.save
    redirect_to things_path    
  end
  
  def unfollow
    id_s = params[:format]
    id = id_s.to_i
    current_user.followed_things_will_change!
    current_user.followed_things.delete(id_s)
    current_user.save


    redirect_to(:back)    
  end
    

  #NEEDSTO BE FIXED 
  def show
    if @thing.user.nil?
      u = User.new
      u.username = "anonymous"
      @thing.user = u 
    end
    @comments = @thing.comments

    #ugh: needed to create a new comment without adding new comment to the list at bottom of thing view
    @comment = Comment.new
    @comment.thing_id = @thing.id
    @comment.user = current_user
  end

  # GET /things/new
  def new
    @thing = Thing.new
    1.times {@thing.solutions.build}
  end



  # POST /things
  # POST /things.json
  def create
    # if current_user.soft_user?
    #   @thing = Thing.new(thing_params)
    #   @thing.solutions.build
    #   if params[:signup]
    #     @thing.soft_token = current_user.soft_token
    #     if @thing.save
    #       flash[:notice]= ['Your need was created.','Sign up to get alerts on solutions!'].join("<br/><br/>").html_safe
    #       redirect_to controller: "users/registrations", action: "new"
    #     end
    #   else
    #     @thing.soft_token = current_user.soft_token
    #     if params[:add_solution]
    #       @thing = current_user.things.build(thing_params)
    #       @thing.solutions.build
    #       render :new
    #       return
    #     end
    #     respond_to do |format|
    #       if @thing.save
    #         format.html { redirect_to new_user_registration_path, notice: 'Thing was successfully created.' }
    #         format.json { render :show, status: :created, location: @thing }
    #       else
    #         format.html { render :new  }
    #         format.json { render json: @thing.errors, status: :unprocessable_entity }
    #       end
    #     end
    #   end

# IF USER IS NOT SOFT USER
      @thing = current_user.things.build(thing_params)  
      if params[:signup] or params[:action] == "home_alt"
        @thing.solutions.build
        # if @thing.save
        #   flash[:notice]= ['Your need was created.','Fill out more details here!'].join("<br/><br/>").html_safe
        #   render :edit and return
        # else
        #   redirect_to :back, alert: "Thing not created, go go 'new thing' view!"
        # end
        respond_to do |format|
          if @thing.save
            format.html { redirect_to new_thing_path, notice: 'Thing was successfully created.' }
            format.json { render :show, status: :created, location: @thing }
          else
            format.html { render :home_alt }
            format.json { render json: @thing.errors, status: :unprocessable_entity }
          end
        end
      else
        if params[:add_solution]
          @thing.solutions.build
          render :new and return
        end
        @thing.solutions.build
        respond_to do |format|
          if @thing.save
            format.html { redirect_to new_thing_path, notice: 'Thing was successfully created.' }
            format.json { render :show, status: :created, location: @thing }
          else
            format.html { render :new  }
            format.json { render json: @thing.errors, status: :unprocessable_entity }
          end
        end
      end
  end
   #     if @solution.save
    #      format.html { redirect_to @solution, notice: 'Solution was successfully created.' }
     #     format.json { render :show, status: :created, location: @solution }
     #   else
      #    format.html { render :new }
       #   format.json { render json: @solution.errors, status: :unprocessable_entity }
       # end
       # => @thing.save
  #     @thing.save    
   #    render :edit
  #end



  



  # GET /things/1/edit  
  def edit
    #refactor w/ udpate to separate method
    unless current_user.id == Thing.find(params[:id]).user_id
      flash[:alert] = "You can only edit your own things!"
      redirect_to(:back) and return 
    end
    @thing.solutions.build if @thing.solutions.empty?
    
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    #refactor w/ edit to separate method
    unless current_user.id == Thing.find(params[:id]).user_id
      flash[:alert] = "You can only edit your own things!"
      redirect_to(:back) and return 
    end    
    if params[:add_solution]
      @thing = Thing.find(params[:id])
      @thing.update(thing_params)
      @thing.solutions.build
      render :edit
      return
    end
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    before_filter :require_admin! #FOR NOW, DON'T WANT PEOPLE TO DESTROY THINGS
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:user_id, :object_description, :problem_description, :solution_description, :tag_list, :user_not_required,  solutions_attributes: [:id, :kind, :description, :issues_description, :link])
#      params.require(:solution).permit(:kind, :description, :issues_description)
    end

   
      

  end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<br>
<%= form_for @thing do |f| %>

  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


	
<div class="row">	
	<div class="col-lg-2">	
		<%= f.label "I want a thing to:" %><br><small><i>(max 200 characters)</i></small>
	</div>
	<div class="col-lg-9">		   
		<%= f.text_area :object_description, placeholder: "do X.", class: "form-control" %>
	</div>
</div>	
<br>

<div class="row">	
	<div class="col-lg-2">	
		<%= f.label "The problem I have:" %><br>
	</div>
	<div class="col-lg-9">		   
		<%= f.text_area :problem_description, placeholder: "pain.", class: "form-control" %>
	</div>
</div>	
<br>    

<div class="row">	
	<div class="col-lg-2">	
		<%= f.label "A possible solution:" %><br>
	</div>
	<div class="col-lg-9">		   
		<%= f.text_area :solution_description, placeholder: "joy.", class: "form-control" %>
	</div>
</div>	
<br>

<div class="row">	
	<div class="col-lg-2">	
		<%= f.label :tag_list, "Tags:" %><br /><small><i>(separated by commas)</i></small>
	</div>
	<div class="col-lg-9">		   
		<%= f.text_field :tag_list, value: @thing.tag_list.to_s, placeholder: "X, joy, pain removal", class: "form-control", id: "formGroupInputSmall"%>
	</div>
</div>	
<br>
    
<div class="row">

	<div class="col-lg-2">	
		<br>		
				
		<b>"Existing solutions:"</b>
		<br><br>
		<%= f.submit 'Add solution', :name => "add_solution", class: "btn btn-default"  %>
	</div>
		
	<div class="col-lg-9">
	<table class="table table-striped">
		<thead>
	    <tr>
	        <th>Link:</th>			
			<th>Type:</th>
	        <th>Description:</th>
	        <th>Problems with this solution:</th>
	      </tr>
	    </thead>

		<tbody>	
<small>
			<%= f.fields_for :solutions do |sol| %>
				<tr>
					<td>    <%= sol.text_field :link,  placeholder: 'http://www.example.com', class: "form-control"%></td>

					<td>    <small>	
							<%= sol.radio_button :kind, 'product'%> 
							<%= label :type_product, 'product' %>
							<br>
							<%= sol.radio_button :kind, 'startup'%> 
							<%= label :type_product, 'startup' %>
							<br>
							<%= sol.radio_button :kind, 'hack'%> 
							<%= label :type_product, 'hack' %>												
						</small>	
					
					</td>
				    <td>    <%= sol.text_area :description, placeholder: "how it works.", class: "form-control" %></td>
				    <td>    <%= sol.text_area :issues_description, placeholder: "its problems.", class: "form-control" %></td>
				</tr>
			<%end%>
</small>
		</tbody>  
	</table>
	</div>
  <div class="actions">
  </div>
</div>

  <%= f.submit "Save Thing", :class => 'btn btn-primary' %>

<% end %>

app/views/things/_form_comment.html.erb
<%= form_for(@comment) do |f| %>

	<%= f.hidden_field :thing_id %>
  <div class="form-horizontal">
  <div class="form-group">
    <div class="col-lg-12">
    	<%= f.text_area :content, placeholder: "Compose new comment...",  class: "form-control" %>
    </div>
    </div>
  </div>

		<%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>

app/views/things/_index.html.erb
<table class="table table-striped">
  <thead>
    <tr>

      <th>Thing to:</th>
      <th>Tags:	</th>
      <th>By:	</th>
      <th>Problem:</th>
      <th>Solution:	</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>

        <td><%= thing.object_description %></td>
		<td><%= raw thing.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        <td><%= thing.user.email %></td>
        <td><%= thing.problem_description %></td>
        <td><%= thing.solution_description %></td>



		
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thing', new_thing_path %>

app/views/things/_index_all.html.erb
<table class="table table-striped">
  <thead>
    <tr>

      <th>Thing to:</th>
      <th>Tags:	</th>
      <th>By:	</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>

        <td><%= link_to thing.object_description, thing %></td>
		<td><%= raw thing.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>

		<% if thing.user == current_user %>
			<td>you</td>
		<%elsif thing.user == nil %>
			<td><i>anonymous</i></td>
		<%else %>
			<td><%= thing.user.username %></td>	
		<% end%>		

		<% if thing.user == current_user %>
			<td></td>
		<%elsif @followed_things_ids.include? thing.id %>
			<td><%= link_to 'Unfollow', unfollow_path(thing) %></td>
		<%else %>
        	<td><%= link_to 'Follow', follow_path(thing) %></td>			
		<%end%>
		
		
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/things/_index_current_user.html.erb
<table class="table table-striped">
  <thead>
    <tr>

      <th>Thing to:</th>
      <th>Tags:	</th>
	  <%unless @followed == false %>
      	<th>By:	</th>
	  <%end%>
      <th colspan="3"></th>


    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>

        <td><%= link_to thing.object_description, thing %></td>
		<td><%= raw thing.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>

  	  <%if @followed == false %>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
  	  <%else%>
        <td><%= thing.user.username %></td>
		
  	  <%end%>






		<% if @followed == true %>
			<td><%= link_to 'Unfollow', unfollow_path(thing) %></td>
		<%end%>
		
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/things/_show_solution.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Link:</th>
        <th>Type:</th>
        <th>Possible solution:</th>
        <th>Problems with this solution:</th>
      </tr>
    </thead>


    <tbody>
		<%for solution in @thing.solutions %>
        <tr>
          <td><%= solution.link %>     </td>
          <td><%= solution.kind %>     </td>
          <td><%= solution.description %>    </td>
          <td><%= solution.issues_description %>   </td>		  		  
        </tr>
		<%end%>
    </tbody>
  </table>

app/views/things/create.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/current_user_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Things</h1>

<%= render 'index' %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

app/views/things/home_alt.html.erb
<% title("Home Page") %>



<!-- STYLING FOR THE FORM -->
<style>
::-webkit-input-placeholder {
 font-size: 20px;
 color: #6b6b6b;
}
</style>

<div class="text-center">
	<!-- <div class="row">
		<br	>
		<div class="col-xs-6 col-centered">
			<div class="text-center">

		<h1>thing to do [X]</h1>

		<p>a wishlist for products that don't exist (yet).</p>
		<br>
		</div>
	</div>
</div> -->


<div class="row">
	<div class="col-xs-8 col-centered">
		<div class="text-center">
			
		</div>
	</div>
</div>

<div class="row">
	<h1>I wish there were a thing to:</h1><!-- <h2><small></small></h2> -->
	<br>

	
    <%= form_for @thing do |f| %>
			<div class="col-xs-6 col-centered">
				<%= f.text_area :object_description, placeholder: "\r\n\r\n\r\nDescribe a problem you have. We'll email you when a product to solves that problem launches.", class: "form-control", rows: 13 %>
<br>
			<!-- <%= f.text_field :tag_list, placeholder: "tags, to make your need searchable", class: "form-control input-lg", rows: 2 %> -->
			</div>
</div>
<div class=row>
	<div class="col-xs-6 col-centered">
	<%= f.submit "post your unsolved problem >", :name => "signup", :class => 'btn btn-primary btn-lg btn-block' %>
	</div>
</div>

	<% end %>



</div>

app/views/things/index.html.erb
<% if params[:tag] %>
	<h1> Things
  	<small>tagged '<%= params[:tag] %>' </small></h1>
<%else%>


  
  
	<h1>All Things</h1><br>
	<div class="row">
	<div class="col-lg-4 form-inline">
		<%= form_tag things_path, method: 'get', html: {role: "form"} do %>
			<p>
			  <%= text_field_tag :search, params[:search], class: "form-control" %>
			  <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
			  <%= link_to "All", things_path, {class: "btn btn-sm btn-link"} %>
			</p>
		<% end %>
	</div>
	</div>
<%end%>
<%= render 'index_all' %>

<div class="text-center">
<%= page_entries_info @things %><br>
  <%= paginate @things %>
</div>

app/views/things/index_current_user.html.erb
<h1>Your Things</h1>

<div class="row">
	<div class="col-lg-6">
		<h1><small>Created:</small></h1>
		<%= render 'index_current_user' %>
	</div>

<%@things = @followed_things%>
<% @followed = true %>

	<div class="col-lg-6">
		<h1><small>Followed:</small></h1>
		<%= render 'index_current_user' %>
	</div>
</div>
<%= link_to 'New Thing', new_thing_path, class: "btn btn-default"  %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

app/views/things/show.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1>Thing to:<small>	<%= @thing.object_description %></small></h1>


	<% if @thing.user == current_user %>

		<%= link_to 'Edit thing', edit_thing_path(@thing), class: "btn btn-default" %>
	
	<%end%>
		</div>
		
</div>
<br>
<p>
  <strong>By user:</strong>
  <%= @thing.user.username %>
</p>

<p>
  <strong>Problem:</strong>
  <%= simple_format(@thing.problem_description) %>
</p>
<br>
<p>
  <strong>Solution idea:</strong>
  <%= simple_format(@thing.solution_description) %>
</p>

<p>
  <strong>Tags:</strong>
  <%= raw @thing.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
</p>

<br>

<h3>Solutions:</h3>

  <%= render 'show_solution' %>

<br>


<h3>Comments:</h3>

<%= render 'form_comment' %>	

<br>

<%if @thing.comments.empty? == false%>
	<h1><small>
		<%= @thing.comments.count %>  <%= "Comment".pluralize(@thing.comments.count)%>
	</small></h1>
<%end%>

<table class="table">

  <%= render @comments %>

</table>