config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                       Controller#Action
#                     root GET    /                                 pages#home
#                     home GET    /home(.:format)                   pages#home
#                   inside GET    /inside(.:format)                 pages#inside
#         new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#            user_password POST   /users/password(.:format)         devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                          PATCH  /users/password(.:format)         devise/passwords#update
#                          PUT    /users/password(.:format)         devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#        user_registration POST   /users(.:format)                  devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                          PATCH  /users(.:format)                  devise/registrations#update
#                          PUT    /users(.:format)                  devise/registrations#update
#                          DELETE /users(.:format)                  devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                          GET    /users/confirmation(.:format)     devise/confirmations#show
#               admin_root GET    /admin(.:format)                  admin/base#index
#              admin_users GET    /admin/users(.:format)            admin/users#index
#                          POST   /admin/users(.:format)            admin/users#create
#           new_admin_user GET    /admin/users/new(.:format)        admin/users#new
#          edit_admin_user GET    /admin/users/:id/edit(.:format)   admin/users#edit
#               admin_user GET    /admin/users/:id(.:format)        admin/users#show
#                          PATCH  /admin/users/:id(.:format)        admin/users#update
#                          PUT    /admin/users/:id(.:format)        admin/users#update
#                          DELETE /admin/users/:id(.:format)        admin/users#destroy
#

Ttdx3::Application.routes.draw do
  root "pages#about"
  
  get 'activities/index'

  resources :solutions
  get 'tags/:tag', to: 'things#index', as: :tag
  resources :things
  resources :comments
  resources :activities
  resources :registration_steps
  

  get "home_alt", to: "things#home_alt"
    

  
  get "inside", to: "pages#inside", as: "inside"

  
  get "follow", to: "things#follow", as: "follow"
  get "unfollow", to: "things#unfollow", as: "unfollow"
    
  get "current_user_things", to: "things#index_current_user", as: "current_user_things"
  
  
#  devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }

  
#  get "home_alt", to: "pages#home_alt"
  
    
   
    
  namespace :admin do
    root "base#index"
    resources :users
    
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :require_admin!

  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)

    @count_user = User.users_count
    @count_activated_user = User.includes(:things).where.not('things.id' => nil).count
    @pct_activated = 100.0 * (@count_activated_user.to_f - 1) / @count_user.to_f

    @count_thing = Thing.count
    @count_comment = Comment.count 
    @count_follows = PublicActivity::Activity.where(trackable_type: "Comment").count
    
  end
end

app/views/admin/base/index.html.erb
<% title("Admin") %>
<h1>Admin <small>Home</small></h1>
<div class="row">
  <div class="col-sm-4">
    <h3>Menu</h3>
    <h4><%= link_to "Users", admin_users_path %> <small>- <%= "#{pluralize(@count_user, 'user')}" %>, <%= number_to_percentage(@pct_activated, precision: 0)%> activated  </small></h4>
    <h4>Things <small>- <%= "#{pluralize(@count_thing, 'thing')}" %></small></h4>
    <h4>Comments <small>- <%= "#{pluralize(@count_comment, 'comment')}" %></small></h4>
    <h4>Follows <small>- <%= "#{pluralize(@count_follows, 'follows')}" %> </small></h4>		
    <hr/>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ups</h3>
    <ul class="list-unstyled">
      <% @last_signups.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small><%= time_ago_in_words(user.created_at)%> ago</small>
      </li>
      <% end %>
    </ul>
  </div>

  <div class="col-sm-4">
    <h3>Last Sign Ins</h3>
    <ul class="list-unstyled">
      <% @last_signins.each do |user| %>
      <li class="list-padded-bottom">
        <%= link_to user.email, edit_admin_user_path(user) %><br/>
        <small>
          <% unless user.last_sign_in_at.nil? %>
          <%= time_ago_in_words(user.last_sign_in_at)%> ago
          <% else %>
          never
          <% end %>
        </small>
      </li>
      <% end %>
    </ul>
  </div>

</div>