config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                       Controller#Action
#                     root GET    /                                 pages#home
#                     home GET    /home(.:format)                   pages#home
#                   inside GET    /inside(.:format)                 pages#inside
#         new_user_session GET    /users/sign_in(.:format)          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)         devise/sessions#destroy
#            user_password POST   /users/password(.:format)         devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)    devise/passwords#edit
#                          PATCH  /users/password(.:format)         devise/passwords#update
#                          PUT    /users/password(.:format)         devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)           devise/registrations#cancel
#        user_registration POST   /users(.:format)                  devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)             devise/registrations#edit
#                          PATCH  /users(.:format)                  devise/registrations#update
#                          PUT    /users(.:format)                  devise/registrations#update
#                          DELETE /users(.:format)                  devise/registrations#destroy
#        user_confirmation POST   /users/confirmation(.:format)     devise/confirmations#create
#    new_user_confirmation GET    /users/confirmation/new(.:format) devise/confirmations#new
#                          GET    /users/confirmation(.:format)     devise/confirmations#show
#               admin_root GET    /admin(.:format)                  admin/base#index
#              admin_users GET    /admin/users(.:format)            admin/users#index
#                          POST   /admin/users(.:format)            admin/users#create
#           new_admin_user GET    /admin/users/new(.:format)        admin/users#new
#          edit_admin_user GET    /admin/users/:id/edit(.:format)   admin/users#edit
#               admin_user GET    /admin/users/:id(.:format)        admin/users#show
#                          PATCH  /admin/users/:id(.:format)        admin/users#update
#                          PUT    /admin/users/:id(.:format)        admin/users#update
#                          DELETE /admin/users/:id(.:format)        admin/users#destroy
#

Ttdx3::Application.routes.draw do
  root "pages#about"
  
  get 'activities/index'

  resources :solutions
  get 'tags/:tag', to: 'things#index', as: :tag
  resources :things
  resources :comments
  resources :activities
  resources :registration_steps
  

  get "home_alt", to: "things#home_alt"
    

  
  get "inside", to: "pages#inside", as: "inside"

  
  get "follow", to: "things#follow", as: "follow"
  get "unfollow", to: "things#unfollow", as: "unfollow"
    
  get "current_user_things", to: "things#index_current_user", as: "current_user_things"
  
  
#  devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }

  
#  get "home_alt", to: "pages#home_alt"
  
    
   
    
  namespace :admin do
    root "base#index"
    resources :users
    
  end

end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">

    <div class="row footer-first-row">

      <div class="col-xs-12 text-center">
        <p><small>
          &copy; <%= Time.now.year %> - ttd[X]
          <br/>
        </small></p>
      </div>

    </div>

  </div>
</div>
<% if Rails.env == "production" %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-38415904-2', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
<% if msg.is_a?(String) %>
<div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
</div>
<% end %>
<% end %>

app/views/layouts/_navigation.html.erb
		  

<% if current_user.id.nil? %>

        <%= render 'layouts/navigation_signed_out' %>

<% else %>

        <%= render 'layouts/navigation_signed_in' %>

<% end %>

app/views/layouts/_navigation_signed_in.html.erb
<nav class="navbar navbar-inverse ">
  <div class="container ">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse">

      <ul class="nav navbar-nav">		 
		  <b><li><%= link_to 'ttd[x]', root_path, class: 'navbar-brand' %></b>
	  </ul>

      <ul class="nav navbar-nav navbar-right">
		  
		  
<li><%= link_to "new thing", new_thing_path %></li>  
<li><%= link_to "your things", current_user_things_path %></li>
<li><%= link_to "all things", things_path %></li>

<% if current_user.admin? %>
	<li><%= link_to "notifs", activities_path %></li>
<% end %>

<% if current_user.admin? %>
	<li><%= link_to "admin", admin_root_path %></li>
<% end %>

<li><%= link_to "account", edit_user_registration_path %></li>





      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_signed_out.erb
<nav class="navbar ">
  <div class="container ">
    <div class="">

      <ul class="nav navbar-nav">
		  
	  </ul>

      <ul class="nav navbar-nav navbar-right">
			  <br>	  

<li><%= link_to "sign in", new_user_session_path %></li>


<!--<li ><%= link_to "sign up", new_user_registration_path, class: 'btn btn-default btn-navbar btn-xs', type: "button" %></li> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Ttdx3" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink="true">
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
	
	<% if Rails.env.development? %>
		<br><br><br><br>
		<%= params %>
		<br>
		<%= current_user.inspect %>
	<% end %>
  </div>
	<br>
	


  <%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application_alt_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "Ttdx3" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">

    <div class="container">

      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>

    </div>
  </div>
	<br>
  <%= render 'layouts/footer' %>

</body>
</html>